# Generated by Django 5.2.3 on 2025-06-11 19:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('number_of_songs', models.PositiveIntegerField(default=0)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('Pop', 'Pop'), ('Rock', 'Rock'), ('Classical', 'Classical'), ('Hip-Hop', 'Hip-Hop'), ('Jazz', 'Jazz'), ('Folk', 'Folk'), ('Country', 'Country'), ('EDM', 'Electronic Dance Music'), ('Other', 'Other')], default='Other', max_length=50)),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
    ]
