# Generated by Django 5.2.2 on 2025-06-10 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.SlugField(default=uuid.uuid4, unique=True)),
                ('active_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('published_year', models.CharField(max_length=4)),
                ('edition', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=20)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('History', 'History'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('Romance', 'Romance')], max_length=30)),
                ('price', models.FloatField()),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('author', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
